### ISSUE TITLE
cmumps_struc.h is not produced

### ISSUE THREAD

**Issue by MatthewCroughan** [scivision/mumps-superbuild#101]
I would have expected this header to be included like it is in other distributions

**Comment by scivision** [comment]
I believe this is referring to `cmake --install build` behavior. By default, MUMPS CMake scripts does not build the complex math functions of MUMPS. To get them, build MUMPS like:

```sh
cmake -Bbuild -DBUILD_SINGLE=on -DBUILD_DOUBLE=on -DBUILD_COMPLEX=on -DBUILD_COMPLEX16=on

cmake --build build

cmake --install build
```

Fixed by 3c8cb3f
