### ISSUE TITLE
Missing related dynamic library libdmumps_seq.so

### ISSUE THREAD

**Issue by liang-jinli** [scivision/mumps-superbuild#22]
I used the tutorial to install mumps, but didn't get libdmumps_seq.so , which is exactly what I needed.
My options.cmake is as follows:

option(autobuild "auto-build Lapack and/or Scalapack if missing or broken" true)
option(BUILD_TESTING "build with testing features" true)
option(dev "developer mode")
option(parallel "parallel or sequential (non-MPI, non-Scalapack)" ON)
option(intsize64 "use 64-bit integers in C and Fortran" OFF)

option(scotch "use Scotch" OFF)
option(openmp "use OpenMP" OFF)

and my directive is as follows:
cmake -B build -DMUMPS_UPSTREAM_VERSION=4.10.0 -DBUILD_SHARED_LIBS=on

**Comment by scivision** [comment]
libdmumps_seq is not a standard component name. different packagers use different names, I try to use the same names as upstream mumps

**Comment by scivision** [comment]
a3c383f78608474c19f71adada3b8ff6e7305dcf documents this
