### ISSUE TITLE
how to link the generated static lib to my visual studio project

### ISSUE THREAD

**Issue by Ning-Li-Ambition** [scivision/mumps-superbuild#24]
hi there,
I use visual studio on windows with intel oneAPI Fortran.
I have never used ninja before, but used cmake to install libraries on windows. my question is, if I follow your instructions, what will I get? A static library? And could I link it to my personal visual studio project?
Thanks

**Comment by scivision** [comment]
Visual Studio will probably not work to build MUMPS, it never has for me at least.
I haven't tried using the static lib files in a Visual Studio project.
With default CMake options and oneAPI on Windows:

```sh
cmake -B build -G Ninja
```

```
-- Building for: Ninja
-- The C compiler identification is IntelLLVM 2022.0.0 with MSVC-like command-line
-- The Fortran compiler identification is IntelLLVM 2022.0.0 with MSVC-like command-line
...
```

```sh
cmake --build build
```

under build/ directory I get static libraries:

```
dmumps.lib
mumps_common.lib
pord.lib
smumps.lib
```

**Comment by scivision** [comment]
I documented this in a3c383f78608474c19f71adada3b8ff6e7305dcf
