### ISSUE TITLE
Import Mumps targets from external projects (not online)

### ISSUE THREAD

**Issue by dariomangoni** [scivision/mumps-superbuild#3]
Hi,
given the quite complex CMake project with lots of dependencies it would be greate if there was a proper and smart way to import Mumps targets from external projects without fetching online. What is the best way?
My external project build with Visual Studio and I wouldn't make it compile with Ninja.

Can you provide a little snippet for it?

I don't see any typical file of CMake Packages so I assume there is none.

**Comment by scivision** [comment]
To compile on Windows, I would recommend using Intel oneAPI
