### ISSUE TITLE
Build failed on Windows+Intel oneAPI

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/mumps-superbuild#36]
System:

Windows 10, VS 2019, Intel oneAPI 2022, lastest master branch

Command line used:

cmake -B build -G Ninja -DCMAKE_C_COMPILER=cl -Dparallel=false

Error:

CMake Error at CMakeLists.txt:69 (add_subdirectory):
  add_subdirectory given source "/libseq" which is not an existing directory.

**Comment by scivision** [comment]
This is fixed in v5.5.1.3 thanks
