### ISSUE TITLE
FindLAPACK cannot find OpenMP on Windows

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/mumps-superbuild#37]
Dear Michael,

It seems that FindLAPACK.cmake can not find components OpenMP on Windows, with Intel oneAPI 2022 and cmake 3.24.0.  The cmake GUI shows that LAPACK_libiomp5md_LIBRARY-NOTFOUND. Could you please take a look when you have some time?

Yours sincerely,
Adam

**Comment by adam-sim-dev** [comment]
It seems that when build MUMPS without MPI but with OpenMP, the LAPACK library links with mkl_sequential.lib.

**Comment by scivision** [comment]
Thanks, I think OpenMP with Intel MKL was accidentally broken for this project for a long time!
