### ISSUE TITLE
error #5102: Cannot open include file 'zmumps_struc.h'

### ISSUE THREAD

**Issue by jdh13** [scivision/mumps-superbuild#4]
Hello,
i am using your doc to include mumps into my project with FetchProject, as you described it.
But got this error when compiling:

```
: error #5102: Cannot open include file 'zmumps_struc.h'
    INCLUDE 'zmumps_struc.h'
------------^
/tmp/ifortVCXhzJ.i90(757): catastrophic error: Too many errors, exiting
```

but this file exists, in the build directory:
```
$ find . -name "zmumps*.h"
./_deps/mumps_proj-src/include/zmumps_c.h
./_deps/mumps_proj-src/include/zmumps_root.h
./_deps/mumps_proj-src/include/zmumps_struc.h
./_deps/mumps_proj-src/src/zmumps_gpu.h
```

Could you help, please?

Thanks in advance

**Comment by scivision** [comment]
I would recommend building MUMPS as ExternalProject in general. We've come to find FetchContent isn't the best solution for this type of project.
