### ISSUE TITLE
ParMetis and scotch ordering options

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/mumps-superbuild#57]
Hi @scivision , could you please add the ParMetis and scotch ordering options support when you have some time?

Best,
Adam

**Comment by scivision** [comment]
Does building with "cmake -Dscotch=yes -Bbuild" work? https://github.com/scivision/mumps/blob/main/Readme_ordering.md

**Comment by adam-sim-dev** [comment]
If with -Dmetis=yes, how to specify the path to find metis?

**Comment by adam-sim-dev** [comment]
Can I use the metis lib build before?

**Comment by scivision** [comment]
Yes I just updated that readme to note how to specify the location of existing METIS and Scotch:

```sh
cmake -Bbuild -DMETIS_ROOT=/path/to/metis -DScotch_ROOT=/path/to/scotch -Dscotch=on
```

**Comment by adam-sim-dev** [comment]
Thanks @scivision . The parmetis support for MUMPS is not so clear from the document.

**Comment by scivision** [comment]
I realized parMETIS was not previously supported in my CMake script.

I just added parMETIS: https://github.com/scivision/mumps/commit/4ca4f09db419f1b95c7a3ee9039648d7ff593c9b

please reopen or make new issue if there's problems
