### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/mumps-superbuild#68]
CMake Error at cmake/mumps.cmake:113 (target_link_libraries):
  Target "mumps_common" links to:

    LAPACK::LAPACK

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  CMakeLists.txt:131 (include)

-- Generating done (0.3s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by adam-sim-dev** [comment]
Caused by the latest commit

**Comment by scivision** [comment]
I see this on Linux Intel oneAPI and Windows Intel oneAPI, is that the compiler you're using?

**Comment by scivision** [comment]
I force-pushed a fix and rereleased, thanks!
