### ISSUE TITLE
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to LOGICAL(4)

### ISSUE THREAD

**Issue by TigerJyf** [scivision/mumps-superbuild#73]
Dear Michael,
make[1]: Entering directory '/home/bbq/package/MUMPS_5.6.2/libseq'
gfortran -O               -c mpi.f -o mpi.o
mpi.f:624:72:

  624 |          CALL MUMPS_COPY_LOGICAL( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to LOGICAL(4)
mpi.f:626:72:

  626 |          CALL MUMPS_COPY_REAL( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to REAL(4)
mpi.f:629:72:

  629 |          CALL MUMPS_COPY_DOUBLE_PRECISION( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to REAL(8)
mpi.f:631:72:

  631 |          CALL MUMPS_COPY_COMPLEX( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to COMPLEX(4)
mpi.f:633:72:

  633 |          CALL MUMPS_COPY_DOUBLE_COMPLEX( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to COMPLEX(8)
mpi.f:635:72:

  635 |          CALL MUMPS_COPY_2DOUBLE_PRECISION( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to REAL(8)
mpi.f:639:72:

  639 |         CALL MUMPS_COPY_INTEGER8( SENDBUF, RECVBUF, CNT )
      |                                                                        1
Error: Type mismatch in argument ‘s’ at (1); passed INTEGER(4) to INTEGER(8)
make[1]: *** [Makefile:25: mpi.o] Error 1
make[1]: Leaving directory '/home/bbq/package/MUMPS_5.6.2/libseq'
make: *** [Makefile:80: libseqneeded] Error 2
how to solve this error?
thanks

**Comment by scivision** [comment]
What options did you use on the command line? MUMPS source code uses a legacy coding style--I only provide CMake script to build unmodified MUMPS source. So there are normally a lot of warnings when building.

On Ubuntu 22.04 I get:

```sh
$ cmake -Bbuild -Dparallel=no
-- The C compiler identification is GNU 11.4.0
-- The Fortran compiler identification is GNU 11.4.0
...
-- CMake 3.22.1  Toolchain
```

This then builds successfully for me.

If you've added CMAKE_C_FLAGS or have set [CMAKE_COMPILE_WARNING_AS_ERROR](https://cmake.org/cmake/help/latest/prop_tgt/COMPILE_WARNING_AS_ERROR.html) to true this error could happen.

**Comment by scivision** [comment]
I am closing this as I believe it may be due to factors in my prior message. Please reopen if it's still an issue.
