### ISSUE TITLE
GEMMT disabled by default for oneAPI 2024 on Windows?

### ISSUE THREAD

**Issue by adam-sim-dev** [scivision/mumps-superbuild#81]
cmake -G Ninja -B build -DCMAKE_INSTALL_PREFIX=.
-- The C compiler identification is IntelLLVM 2024.0.2 with MSVC-like command-line
-- The Fortran compiler identification is IntelLLVM 2024.0.2 with MSVC-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/icx.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Check for working Fortran compiler: C:/Program Files (x86)/Intel/oneAPI/compiler/latest/bin/ifx.exe - skipped
-- MUMPS 5.6.2.2 upstream 5.6.2 install prefix: C:/Users/adam/Documents/MUMPS_5.6.2
-- CMake 3.29.0  Toolchain
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Found MPI_C: C:/Program Files (x86)/Intel/oneAPI/mpi/latest/lib/impi.lib (found version "3.1")
-- Found MPI_Fortran: C:/Program Files (x86)/Intel/oneAPI/mpi/latest/lib/impi.lib (found version "3.1")
-- Found MPI: TRUE (found version "3.1") found components: C Fortran
-- MKL_VERSION: 2024.0.0
-- MKL_ROOT: C:/Program Files (x86)/Intel/oneAPI/mkl/latest
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: intel_lp64
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_MPI: None, set to ` intelmpi` by default
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/mkl_scalapack_lp64_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/latest/bin/mkl_scalapack_lp64.2.dll
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/mkl_intel_lp64_dll.lib
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/mkl_intel_thread_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/latest/bin/mkl_intel_thread.2.dll
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/mkl_core_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/latest/bin/mkl_core.2.dll
-- Found C:/Program Files (x86)/Intel/oneAPI/mkl/latest/lib/mkl_blacs_lp64_dll.lib
-- Found DLL: C:/Program Files (x86)/Intel/oneAPI/mkl/latest/bin/mkl_blacs_lp64.2.dll
-- Found C:/Program Files (x86)/Intel/oneAPI/compiler/latest/lib/libiomp5md.lib
-- Performing Test SCALAPACK_d_FOUND
-- Performing Test SCALAPACK_d_FOUND - Success
-- Performing Test SCALAPACK_s_FOUND
-- Performing Test SCALAPACK_s_FOUND - Success
-- Found SCALAPACK: $<IF:$<BOOL:OFF>,,>;MKL::mkl_scalapack_lp64;MKL::mkl_intel_lp64;MKL::mkl_intel_thread;MKL::mkl_core;MKL::mkl_blacs_lp64;C:/Program Files (x86)/Intel/oneAPI/compiler/latest/lib/libiomp5md.lib  found components: MKL
-- MUMPS ORDERING_DEFS: pord
-- MUMPS ORDERING_LIBS: pord
-- Populating mumps
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: C:/Users/adam/Documents/MUMPS_5.6.2/build/_deps/mumps-subbuild
-- Downloading...
   dst='C:/Users/adam/Documents/MUMPS_5.6.2/build/_deps/mumps-subbuild/mumps-populate-prefix/src/MUMPS_5.6.2.tar.gz'
   timeout='none'
   inactivity timeout='none'
-- Using src='https://mumps-solver.org/MUMPS_5.6.2.tar.gz'
-- [download 0% complete]
-- [download 1% complete]
-- [download 2% complete]
-- [download 4% complete]
-- [download 5% complete]
-- [download 8% complete]
-- [download 9% complete]
-- [download 10% complete]
-- [download 14% complete]
-- [download 16% complete]
-- [download 19% complete]
-- [download 22% complete]
-- [download 24% complete]
-- [download 27% complete]
-- [download 31% complete]
-- [download 34% complete]
-- [download 36% complete]
-- [download 37% complete]
-- [download 40% complete]
-- [download 42% complete]
-- [download 46% complete]
-- [download 50% complete]
-- [download 54% complete]
-- [download 58% complete]
-- [download 59% complete]
-- [download 62% complete]
-- [download 63% complete]
-- [download 64% complete]
-- [download 68% complete]
-- [download 70% complete]
-- [download 75% complete]
-- [download 79% complete]
-- [download 83% complete]
-- [download 87% complete]
-- [download 91% complete]
-- [download 95% complete]
-- [download 99% complete]
-- [download 100% complete]
-- verifying file...
       file='C:/Users/adam/Documents/MUMPS_5.6.2/build/_deps/mumps-subbuild/mumps-populate-prefix/src/MUMPS_5.6.2.tar.gz'
-- Downloading... done
-- extracting...
     src='C:/Users/adam/Documents/MUMPS_5.6.2/build/_deps/mumps-subbuild/mumps-populate-prefix/src/MUMPS_5.6.2.tar.gz'
     dst='C:/Users/adam/Documents/MUMPS_5.6.2/mumps/5.6.2'
-- extracting... [tar xfz]
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
[1/9] Creating directories for 'mumps-populate'
[1/9] Performing download step (download, verify and extract) for 'mumps-populate'
[2/9] No update_disconnected step for 'mumps-populate'
[3/9] No patch_disconnected step for 'mumps-populate'
[5/9] No configure step for 'mumps-populate'
[6/9] No build step for 'mumps-populate'
[7/9] No install step for 'mumps-populate'
[8/9] No test step for 'mumps-populate'
[9/9] Completed 'mumps-populate'
-- Configured MUMPS 5.6.2 source in C:/Users/adam/Documents/MUMPS_5.6.2/mumps/5.6.2
-- The following features have been enabled:

 * Parallel, parallel MUMPS (using MPI and Scalapack)
 * real32, Build with single precision
 * real64, Build with double precision

-- The following features have been disabled:

 * 64-bit-integer, use 64-bit integers in C and Fortran
 * GEMMT, use GEMMT for symmetric matrix-matrix multiplication
 * METIS, METIS graph partitioning https://github.com/KarypisLab/METIS
 * parMETIS, parMETIS parallel graph partitioning
 * Scotch, Scotch graph partitioning https://www.labri.fr/perso/pelegrin/scotch/
 * Openmp, OpenMP API https://www.openmp.org/
 * complex32, Build with complex precision
 * complex64, Build with complex16 precision
 * shared, Build shared libraries

-- Configuring done (12.7s)
-- Generating done (0.1s)
-- Build files have been written to: C:/Users/adam/Documents/MUMPS_5.6.2/build

**Comment by scivision** [comment]
Thank you, [https://github.com/scivision/mumps/commit/9c448a1da2301c0c20eb32ea64683c6d6f850cf5](https://github.com/scivision/mumps/releases/tag/v5.6.2.3) fixes this now.
